spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:43306/TESTDB?allowMultiQueries=true
    username: root
    password: 1234
    hikari:
      connection-timeout: 3000
      max-lifetime: 1740000
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        storage-engine: innodb
        hbm2ddl-auto: none  # must be none
        show-sql: true
        format_sql: true          # 포매터 적용
        use_sql_comments: true    # jpql 출력

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always # always: 배치 메타테이블 항상 생성 / never: 생성하지 않음 / embedded: H2 DB 인 경우 생성

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor.sql.basicBinder: TRACE
          BasicTypeRegistry: WARN
        transaction.JDBCTransaction: DEBUG
        jdbc.connectionManager: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.data.repository.config: ERROR
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR
    com.zaxxer.hikari: DEBUG
    jdbc:
      audit: off
      connection: off
      sqlonly: debug
      resultset: off
      resultsettable: info
      sqltiming: debug
    com.ani.study: info